{
 "title": "Sean Thesis Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Number of Twitter Messages",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(id) from messages;"
    }
   ]
  },
  {
   "title": "Total Number of Registered Users",
   "type": "singlestat",
   "description": "Total Number of Registered Users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "select count(id) from users;" }
   ]
  },
  {
   "title": "Total Number of Posts",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select count(id) from posts;" }
   ]
  },
  {
   "title": "Total Number of Defined Roles",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select count(id) from roles;" }
   ]
  }
 ]
}